services:
  backend:
    image: kedro-api
    container_name: kedro_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: angular-frontend-image
    container_name: angular_frontend
    ports:
      - "4200:80"
    restart: unless-stopped
